"use strict";
const UPSTREAM='https://api.mzyyun.com/public/qso',CALL='BA4THG';
const $=s=>document.querySelector(s),token=$('[data-token]'),connect=$('[data-connect]'),conn=$('[data-connection]'),adminContent=$('[data-admin-content]'),form=$('[data-entry-form]'),resetBtn=$('[data-reset]'),submit=$('[data-submit]'),op=$('[data-operation]'),adminList=$('[data-admin-list]'),adminError=$('[data-admin-error]'),refresh=$('[data-refresh]'),importFile=$('[data-import-file]'),importBtn=$('[data-import]'),importState=$('[data-import-state]'),syncBtn=$('[data-sync]'),syncState=$('[data-sync-state]');
let records=[];
function key(){return token.value.trim()}
function state(n,m,t=''){n.textContent=m;n.className=`status${t?' '+t:''}`}
function sourceName(v){const x=String(v||'').toLowerCase();if(x==='mzyyun_api'||x==='mzyyun_api_browser')return'近期同步';if(x==='adif_import')return'ADIF 文件导入';if(x==='csv_import')return'CSV 文件导入';if(x==='json_import')return'JSON 文件导入';if(x==='local'||x==='manual')return'手工录入';return v||'本站记录'}
async function api(path,init={}){if(!key())throw new Error('请先输入管理令牌');const h=new Headers(init.headers||{});h.set('authorization',`Bearer ${key()}`);if(init.body&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(path,{...init,headers:h});const ct=r.headers.get('content-type')||'',d=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(d?.error||d||`请求失败：${r.status}`);return{response:r,data:d}}
function localValue(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function reset(){form.reset();form.elements.id.value='';form.elements.myCallsign.value=CALL;form.elements.mode.value='FM';form.elements.qsoDatetime.value=localValue();form.elements.isPublic.checked=true;submit.textContent='保存记录';state(op,'')}
function payload(){const d=new FormData(form);return{myCallsign:String(d.get('myCallsign')||'').trim().toUpperCase(),theirCallsign:String(d.get('theirCallsign')||'').trim().toUpperCase(),qsoDatetime:new Date(String(d.get('qsoDatetime'))).toISOString(),frequency:d.get('frequency')||null,mode:String(d.get('mode')||'').trim().toUpperCase(),myPower:d.get('myPower')||null,myEquipment:d.get('myEquipment')||null,myAntenna:d.get('myAntenna')||null,myQth:d.get('myQth')||null,theirQth:d.get('theirQth')||null,rstSent:d.get('rstSent')||null,rstReceived:d.get('rstReceived')||null,notes:d.get('notes')||null,qslSent:d.get('qslSent')==='on',qslReceived:d.get('qslReceived')==='on',isPublic:d.get('isPublic')==='on'}}
function fmt(x){const d=new Date(x);return Number.isNaN(d.getTime())?x:new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}
function record(x){const a=document.createElement('article');a.className='qso-record';const p=document.createElement('div');p.className='record-primary';p.innerHTML=`<strong></strong><time></time><span></span>`;p.querySelector('strong').textContent=x.theirCallsign;p.querySelector('time').textContent=fmt(x.qsoDatetime);p.querySelector('span').textContent=`${x.frequency||'—'} MHz · ${x.mode||'—'} · ${x.myPower?x.myPower+' W':'功率未填写'}`;const dl=document.createElement('dl');dl.className='record-details';for(const[k,v]of[['设备',x.myEquipment],['天线',x.myAntenna],['本台地点',x.myQth],['对方地点',x.theirQth],['RST',`${x.rstSent||'—'} / ${x.rstReceived||'—'}`],['记录来源',sourceName(x.source)]]){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v||'—';d.append(dt,dd);dl.append(d)}const acts=document.createElement('div');acts.className='record-actions';const e=document.createElement('button'),del=document.createElement('button');e.textContent='编辑';del.textContent='移入回收站';del.className='danger';e.onclick=()=>edit(x);del.onclick=()=>remove(x);acts.append(e,del);a.append(p,dl,acts);return a}
function edit(x){form.elements.id.value=x.id;for(const n of['myCallsign','theirCallsign','frequency','mode','myPower','myEquipment','myAntenna','myQth','theirQth','rstSent','rstReceived','notes'])if(form.elements[n])form.elements[n].value=x[n]||'';form.elements.qsoDatetime.value=localValue(new Date(x.qsoDatetime));form.elements.qslSent.checked=!!x.qslSent;form.elements.qslReceived.checked=!!x.qslReceived;form.elements.isPublic.checked=x.isPublic!==false;submit.textContent='保存修改';form.scrollIntoView({behavior:'smooth'})}
async function remove(x){if(!confirm(`确认将 ${x.theirCallsign} 的这条通联记录移入回收站？`))return;try{await api(`./api/admin/qsos/${encodeURIComponent(x.id)}`,{method:'DELETE'});state(op,'记录已移入回收站。','success');await load()}catch(e){state(op,e.message,'error')}}
async function load(){adminError.hidden=true;try{const{data}=await api('./api/admin/qsos?limit=50');records=data.items||[];const f=document.createDocumentFragment();for(const x of records)f.append(record(x));adminList.replaceChildren(f);conn.textContent=`已验证 · 共 ${data.total} 条记录`;adminContent.hidden=false;sessionStorage.setItem('ba4thg-qso-token',key())}catch(e){adminContent.hidden=true;adminError.textContent=e.message;adminError.hidden=false;conn.textContent='验证失败'}}
form.addEventListener('submit',async e=>{e.preventDefault();submit.disabled=true;try{const id=form.elements.id.value;await api(id?`./api/admin/qsos/${encodeURIComponent(id)}`:'./api/admin/qsos',{method:id?'PATCH':'POST',body:JSON.stringify(payload())});state(op,id?'修改已保存。':'通联记录已保存。','success');reset();await load()}catch(err){state(op,err.message,'error')}finally{submit.disabled=false}});
function parseAdif(text){const out=[];for(const raw of text.split(/<EOR\s*>/i)){const f={},re=/<([A-Z0-9_]+):(\d+)(?::[^>]*)?>([^<]*)/gi;let m;while((m=re.exec(raw)))f[m[1].toUpperCase()]=m[3].slice(0,+m[2]);if(!f.CALL||!f.QSO_DATE)continue;const t=(f.TIME_ON||'000000').padEnd(6,'0').slice(0,6),d=f.QSO_DATE;out.push({sourceId:f.APP_QSO_ID||d+t+f.CALL,myCallsign:f.STATION_CALLSIGN||f.OPERATOR||CALL,theirCallsign:f.CALL,qsoDatetime:`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}T${t.slice(0,2)}:${t.slice(2,4)}:${t.slice(4,6)}Z`,frequency:f.FREQ||null,band:f.BAND||null,mode:f.MODE||f.SUBMODE||'UNKNOWN',rstSent:f.RST_SENT||null,rstReceived:f.RST_RCVD||null,myQth:f.MY_QTH||null,theirQth:f.QTH||null,myGrid:f.MY_GRIDSQUARE||null,theirGrid:f.GRIDSQUARE||null,myEquipment:f.MY_RIG||null,myAntenna:f.MY_ANTENNA||null,myPower:f.TX_PWR||null,notes:f.COMMENT||f.NOTES||null,qslSent:f.QSL_SENT==='Y',qslReceived:f.QSL_RCVD==='Y',isPublic:true})}return out}
function parseCsv(text){const lines=text.replace(/\r/g,'').split('\n').filter(Boolean),h=(lines.shift()||'').split(',').map(x=>x.trim());return lines.map((line,i)=>{const v=line.split(',');const o={sourceId:`csv-${i+1}`};h.forEach((k,j)=>o[k]=v[j]?.trim()||null);return o})}
async function importData(){const file=importFile.files?.[0];if(!file)return state(importState,'请先选择要导入的文件。','error');importBtn.disabled=true;try{const text=await file.text(),lower=file.name.toLowerCase();let source,items;if(/\.adi(f)?$/.test(lower)){source='adif_import';items=parseAdif(text)}else if(lower.endsWith('.csv')){source='csv_import';items=parseCsv(text)}else{source='json_import';const j=JSON.parse(text);items=Array.isArray(j)?j:(j.qsos||j.records||[])}if(!items.length)throw new Error('文件中没有识别到可导入的通联记录');let ins=0,skip=0,rej=0;for(let i=0;i<items.length;i+=100){state(importState,`正在导入第 ${i+1}–${Math.min(i+100,items.length)} 条，共 ${items.length} 条……`);const{data}=await api('./api/admin/import',{method:'POST',body:JSON.stringify({source,records:items.slice(i,i+100)})});ins+=+data.inserted||0;skip+=+data.skippedAsDuplicate||0;rej+=data.rejected?.length||0}state(importState,`导入完成：新增 ${ins} 条，重复 ${skip} 条，无效 ${rej} 条。`,'success');await load()}catch(e){state(importState,e.message,'error')}finally{importBtn.disabled=false}}
async function upstreamPage(page){const u=new URL(UPSTREAM);u.searchParams.set('callsign',CALL);u.searchParams.set('role','operator');u.searchParams.set('page',page);u.searchParams.set('limit','50');const r=await fetch(u,{mode:'cors',credentials:'omit',headers:{accept:'application/json'}}),d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===403)throw new Error('当前站点尚未获得数据源访问权限，请检查站点接入配置。');throw new Error(d.error||`同步请求失败：${r.status}`)}if(d.station&&String(d.station).toUpperCase()!==CALL)throw new Error('当前站点与记录归属不一致，请检查数据源绑定设置。');return d}
async function sync(){if(!key())throw new Error('请先输入管理令牌');const first=await upstreamPage(1),pages=Math.max(1,Math.ceil((+first.total||0)/50));let fetched=0,inserted=0,updated=0,linked=0,rejected=0;for(let p=1;p<=pages;p++){state(syncState,`正在读取第 ${p}/${pages} 页……`);const d=p===1?first:await upstreamPage(p);if(!d.items?.length)continue;const{data}=await api('./api/admin/import-upstream',{method:'POST',body:JSON.stringify({station:d.station||CALL,items:d.items})});fetched+=+data.fetched||0;inserted+=+data.inserted||0;updated+=+data.updated||0;linked+=+data.linkedToExisting||0;rejected+=+data.rejected||0}return{total:+first.total||0,fetched,inserted,updated,linked,rejected}}
async function exportData(format){try{const r=await fetch(`./api/admin/export?format=${format}`,{headers:{authorization:`Bearer ${key()}`}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`导出失败：${r.status}`)}const b=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`ba4thg-qso.${format==='adif'?'adi':'json'}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){state(op,e.message,'error')}}
connect.onclick=load;refresh.onclick=load;resetBtn.onclick=reset;importBtn.onclick=importData;syncBtn.onclick=async()=>{syncBtn.disabled=true;try{state(syncState,'正在准备同步近期记录……');const d=await sync();state(syncState,`同步完成：读取 ${d.total} 条；归档 ${d.fetched} 条，新增 ${d.inserted} 条，更新 ${d.updated} 条，关联已有 ${d.linked} 条，无效 ${d.rejected} 条。`,'success');await load()}catch(e){state(syncState,e.message,'error')}finally{syncBtn.disabled=false}};document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportData(b.dataset.export));token.value=sessionStorage.getItem('ba4thg-qso-token')||'';adminContent.hidden=true;reset();if(token.value)load();
