"use strict";
const form=document.querySelector('[data-query-form]'),list=document.querySelector('[data-list]'),loading=document.querySelector('[data-loading]'),errorBox=document.querySelector('[data-error]'),empty=document.querySelector('[data-empty]'),pagination=document.querySelector('[data-pagination]'),prev=document.querySelector('[data-prev]'),next=document.querySelector('[data-next]'),pageLabel=document.querySelector('[data-page-label]'),meta=document.querySelector('[data-result-meta]'),summary=document.querySelector('[data-summary]');
const state={page:1,limit:20,total:0,busy:false};
const txt=(v,f='—')=>v===null||v===undefined||v===''?f:String(v);
function fmt(iso){const d=new Date(iso);return Number.isNaN(d.getTime())?txt(iso):new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function detail(dl,k,v){const d=el('div');d.append(el('dt','',k),el('dd','',txt(v)));dl.append(d)}
function card(x){const a=el('article','qso-record'),p=el('div','record-primary');p.append(el('strong','',txt(x.theirCallsign)),el('time','',fmt(x.qsoDatetime)),el('span','',`${txt(x.frequency)} MHz · ${txt(x.mode)} · ${txt(x.band)}`));const dl=el('dl','record-details');detail(dl,'设备',x.myEquipment);detail(dl,'天线',x.myAntenna);detail(dl,'功率',x.myPower?`${x.myPower} W`:null);detail(dl,'本台 QTH',x.myQth);detail(dl,'对方 QTH',x.theirQth);detail(dl,'RST',x.rstSent||x.rstReceived?`${txt(x.rstSent)} / ${txt(x.rstReceived)}`:null);const flags=el('div','flags');flags.append(el('span',`flag${x.qslSent?' on':''}`,x.qslSent?'QSL 已寄':'QSL 未寄'),el('span',`flag${x.qslReceived?' on':''}`,x.qslReceived?'QSL 已收':'QSL 未收'));a.append(p,dl,flags);if(x.notes)a.append(el('p','record-note',x.notes));return a}
function params(){const d=new FormData(form);return{callsign:String(d.get('callsign')||'').trim().toUpperCase(),role:String(d.get('role')||'operator'),year:String(d.get('year')||'').trim(),mode:String(d.get('mode')||'').trim().toUpperCase(),band:String(d.get('band')||'').trim()}}
function renderPages(){const pages=Math.max(1,Math.ceil(state.total/state.limit));pageLabel.textContent=`第 ${state.page} / ${pages} 页`;prev.disabled=state.page<=1||state.busy;next.disabled=state.page>=pages||state.busy;pagination.hidden=state.total<=state.limit}
function renderSummary(d){const s=d.summary||{};document.querySelector('[data-summary-qso]').textContent=s.qsoCount??d.total??0;document.querySelector('[data-summary-contact]').textContent=s.contactCount??0;document.querySelector('[data-summary-sent]').textContent=s.qslSentCount??0;document.querySelector('[data-summary-received]').textContent=s.qslReceivedCount??0;summary.hidden=false}
async function load(){if(state.busy)return;state.busy=true;loading.hidden=false;errorBox.hidden=true;empty.hidden=true;list.replaceChildren();const p=params(),q=new URLSearchParams({callsign:p.callsign,role:p.role,page:String(state.page),limit:String(state.limit)});if(p.year)q.set('year',p.year);if(p.mode)q.set('mode',p.mode);if(p.band)q.set('band',p.band);const u=new URL(location.href);for(const[k,v]of q)u.searchParams.set(k,v);history.replaceState(null,'',u);try{const r=await fetch(`./api/public/qsos?${q}`,{headers:{accept:'application/json'}}),d=await r.json();if(!r.ok)throw new Error(d.error||'查询失败');state.total=Number(d.total||0);state.limit=Number(d.limit||state.limit);meta.textContent=`共 ${state.total} 条公开记录 · ${p.role==='operator'?'本台':'对方'} ${p.callsign}`;renderSummary(d);const f=document.createDocumentFragment();for(const x of d.items||[])f.append(card(x));list.append(f);empty.hidden=state.total>0}catch(e){errorBox.textContent=e.message||'查询失败';errorBox.hidden=false;state.total=0;meta.textContent='查询失败。'}finally{state.busy=false;loading.hidden=true;renderPages()}}
form.addEventListener('submit',e=>{e.preventDefault();state.page=1;load()});prev.addEventListener('click',()=>{if(state.page>1){state.page--;load()}});next.addEventListener('click',()=>{if(state.page*state.limit<state.total){state.page++;load()}});const u=new URL(location.href);for(const n of['callsign','role','year','mode','band'])if(u.searchParams.has(n)&&form.elements[n])form.elements[n].value=u.searchParams.get(n);state.page=Math.max(1,parseInt(u.searchParams.get('page')||'1',10)||1);load();
