"use strict";
const UPSTREAM='https://api.mzyyun.com/public/qso',STATION='BA4THG';
const form=document.querySelector('[data-query-form]'),list=document.querySelector('[data-list]'),loading=document.querySelector('[data-loading]'),errorBox=document.querySelector('[data-error]'),empty=document.querySelector('[data-empty]'),pagination=document.querySelector('[data-pagination]'),prev=document.querySelector('[data-prev]'),next=document.querySelector('[data-next]'),pageLabel=document.querySelector('[data-page-label]'),meta=document.querySelector('[data-result-meta]');
const state={page:1,limit:20,total:0,busy:false};
const txt=(v,f='—')=>v===null||v===undefined||v===''?f:String(v);
const power=v=>v===null||v===undefined||v===''?'—':`${v} W`;
function fmt(iso){const d=new Date(iso);return Number.isNaN(d.getTime())?txt(iso):new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function field(parent,k,v){const row=el('div','station-field');row.append(el('span','field-label',k),el('span','field-value',txt(v)));parent.append(row)}
function station(title,x,side){const box=el('section','station-side');box.append(el('h3','station-call',title));field(box,'地点',side==='their'?x.theirQth:x.myQth);field(box,'设备',side==='their'?x.theirEquipment:x.myEquipment);field(box,'天线',side==='their'?x.theirAntenna:x.myAntenna);field(box,'功率',power(side==='their'?x.theirPower:x.myPower));field(box,'天气',side==='their'?x.theirWeather:x.weather);return box}
function card(x){const a=el('article','qso-record'),head=el('div','record-head'),summary=el('div','record-summary');summary.append(el('strong','',`${txt(x.theirCallsign)} ↔ ${txt(x.myCallsign)}`),el('span','',`${fmt(x.qsoDatetime)} · ${txt(x.mode)} · ${x.frequency?`${x.frequency} MHz`:'频率未记录'} · RST ${txt(x.rstSent)}/${txt(x.rstReceived)}`));const flags=el('div','flags');if(x.live)flags.append(el('span','flag live','近期实时'));flags.append(el('span',`flag${x.qslSent?' on':''}`,x.qslSent?'已寄 QSL':'未寄 QSL'),el('span',`flag${x.qslReceived?' on':''}`,x.qslReceived?'已收 QSL':'未收 QSL'));head.append(summary,flags);const pair=el('div','station-pair');pair.append(station(txt(x.theirCallsign),x,'their'),station(txt(x.myCallsign),x,'my'));a.append(head,pair);if(x.notes){const note=el('div','record-note');note.append(el('span','field-label','备注'),el('span','field-value',x.notes));a.append(note)}return a}
function query(){return String(new FormData(form).get('q')||'').trim()}
function haystack(x){return [x.myCallsign,x.theirCallsign,x.myQth,x.theirQth,x.myEquipment,x.theirEquipment,x.myAntenna,x.theirAntenna,x.frequency,x.mode,x.band,x.notes,x.weather,x.theirWeather,x.rstSent,x.rstReceived].filter(Boolean).join(' ').toLowerCase()}
function matches(x,q){return !q||haystack(x).includes(q.toLowerCase())}
function key(x){return [String(x.myCallsign||'').toUpperCase(),String(x.theirCallsign||'').toUpperCase(),new Date(x.qsoDatetime||0).toISOString?.()||x.qsoDatetime,String(x.frequency||''),String(x.mode||'').toUpperCase()].join('|')}
function normalizeLive(x){return{...x,myCallsign:String(x.myCallsign||STATION).toUpperCase(),theirCallsign:String(x.theirCallsign||'').toUpperCase(),qsoDatetime:x.qsoDatetime||x.qsoDatetimeUtc,frequency:x.frequency??x.frequencyDisplay??null,myPower:x.myPower??x.myPowerW??null,theirPower:x.theirPower??x.theirPowerW??null,live:true}}
async function upstreamPage(page){const u=new URL(UPSTREAM);u.searchParams.set('callsign',STATION);u.searchParams.set('role','operator');u.searchParams.set('page',String(page));u.searchParams.set('limit','50');const r=await fetch(u,{mode:'cors',credentials:'omit',cache:'no-store',headers:{accept:'application/json'}});if(!r.ok)throw new Error(`第三方接口返回 ${r.status}`);const d=await r.json();return d}
async function loadLive(q){try{const first=await upstreamPage(1),pages=Math.min(20,Math.max(1,Math.ceil((Number(first.total)||0)/50))),all=[...(first.items||[])];for(let p=2;p<=pages;p++){const d=await upstreamPage(p);all.push(...(d.items||[]))}return all.map(normalizeLive).filter(x=>matches(x,q))}catch{return[]}}
function renderPages(){const pages=Math.max(1,Math.ceil(state.total/state.limit));pageLabel.textContent=`第 ${state.page} / ${pages} 页`;prev.disabled=state.page<=1||state.busy;next.disabled=state.page>=pages||state.busy;pagination.hidden=state.total<=state.limit}
async function load(){if(state.busy)return;state.busy=true;loading.hidden=false;errorBox.hidden=true;empty.hidden=true;list.replaceChildren();const q=query(),p=new URLSearchParams({page:String(state.page),limit:String(state.limit)});if(q)p.set('q',q);const u=new URL(location.href);u.search='';if(q)u.searchParams.set('q',q);if(state.page>1)u.searchParams.set('page',String(state.page));history.replaceState(null,'',u);try{const [archivedResponse,live]=await Promise.all([fetch(`./api/public/qsos?${p}`,{headers:{accept:'application/json'},cache:'no-store'}),loadLive(q)]),archived=await archivedResponse.json();if(!archivedResponse.ok)throw new Error(archived.error||'查询失败');const archivedItems=archived.items||[],seen=new Set(archivedItems.map(key)),fresh=live.filter(x=>!seen.has(key(x))),combined=[...fresh,...archivedItems].sort((a,b)=>new Date(b.qsoDatetime)-new Date(a.qsoDatetime));state.total=Math.max(Number(archived.total||0),combined.length);state.limit=Number(archived.limit||state.limit);const shown=combined.slice(0,state.limit);meta.textContent=q?`“${q}” · ${shown.length?`找到 ${state.total} 条相关记录`:'没有匹配记录'}`:`BA4THG · 当前显示 ${shown.length} 条记录`;const f=document.createDocumentFragment();for(const x of shown)f.append(card(x));list.append(f);empty.hidden=shown.length>0}catch(e){errorBox.textContent=e.message||'查询失败';errorBox.hidden=false;state.total=0;meta.textContent='查询失败'}finally{state.busy=false;loading.hidden=true;renderPages()}}
form.addEventListener('submit',e=>{e.preventDefault();state.page=1;load()});prev.addEventListener('click',()=>{if(state.page>1){state.page--;load()}});next.addEventListener('click',()=>{if(state.page*state.limit<state.total){state.page++;load()}});
const u=new URL(location.href),legacy=String(u.searchParams.get('callsign')||'').trim().toUpperCase();form.elements.q.value=u.searchParams.get('q')||(legacy&&legacy!==STATION?legacy:'');state.page=Math.max(1,parseInt(u.searchParams.get('page')||'1',10)||1);load();
