import{isValidCallsign,normalizeCallsign}from'./http.js';
export function normalizeMode(v){return String(v??'').trim().toUpperCase()||'UNKNOWN'}
export function normalizeIsoDate(v){const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('通联时间无效');return d.toISOString()}
export function parseFrequencyHz(v){if(v===null||v===undefined||v==='')return null;const raw=typeof v==='string'?v.trim().replace(/\s*MHz\s*$/i,''):v,n=Number(raw);if(!Number.isFinite(n)||n<=0)throw new Error('频率无效');return Math.round(n<1_000_000?n*1_000_000:n)}
export function inferBand(hz){if(!hz)return null;const m=hz/1e6,r=[[1.8,2,'160m'],[3.5,4,'80m'],[7,7.3,'40m'],[10.1,10.15,'30m'],[14,14.35,'20m'],[18.068,18.168,'17m'],[21,21.45,'15m'],[24.89,24.99,'12m'],[28,29.7,'10m'],[50,54,'6m'],[144,148,'2m'],[420,450,'70cm'],[1240,1300,'23cm']].find(([a,b])=>m>=a&&m<=b);return r?r[2]:null}
const text=(v,n=500)=>{const s=String(v??'').trim();return s?s.slice(0,n):null};
const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error('功率无效');return n};
const bit=(v,f=0)=>v===undefined||v===null?f:(v===true||v===1||v==='1'?1:0);
export function normalizeQsoInput(input,defaults={}){const my=normalizeCallsign(input.myCallsign??input.my_callsign??defaults.myCallsign??'BA4THG'),their=normalizeCallsign(input.theirCallsign??input.their_callsign);if(!isValidCallsign(my))throw new Error('本台呼号格式无效');if(!isValidCallsign(their))throw new Error('对方呼号格式无效');const dt=normalizeIsoDate(input.qsoDatetime??input.qsoDatetimeUtc??input.qso_datetime_utc),hz=parseFrequencyHz(input.frequencyHz??input.frequency_hz??input.frequency??input.frequency_display),display=hz?(hz/1e6).toFixed(6).replace(/0+$/,'').replace(/\.$/,''):null;return{myCallsign:my,theirCallsign:their,qsoDatetimeUtc:dt,frequencyHz:hz,frequencyDisplay:display,band:text(input.band,16)??inferBand(hz),mode:normalizeMode(input.mode),rstSent:text(input.rstSent??input.rst_sent,16),rstReceived:text(input.rstReceived??input.rst_received,16),myQth:text(input.myQth??input.my_qth,160),theirQth:text(input.theirQth??input.their_qth,160),myGrid:text(input.myGrid??input.my_grid,16),theirGrid:text(input.theirGrid??input.their_grid??input.grid,16),myEquipment:text(input.myEquipment??input.my_equipment,200),theirEquipment:text(input.theirEquipment??input.their_equipment,200),myAntenna:text(input.myAntenna??input.my_antenna,200),theirAntenna:text(input.theirAntenna??input.their_antenna,200),myPowerW:num(input.myPowerW??input.my_power_w??input.myPower),theirPowerW:num(input.theirPowerW??input.their_power_w??input.theirPower),notes:text(input.notes,2000),weather:text(input.weather,120),theirWeather:text(input.theirWeather??input.their_weather,120),qslSent:bit(input.qslSent??input.qsl_sent),qslSentAt:(input.qslSentAt??input.qsl_sent_at)?normalizeIsoDate(input.qslSentAt??input.qsl_sent_at):null,qslReceived:bit(input.qslReceived??input.qsl_received),qslReceivedAt:(input.qslReceivedAt??input.qsl_received_at)?normalizeIsoDate(input.qslReceivedAt??input.qsl_received_at):null,isPublic:bit(input.isPublic??input.is_public,1)}}
export async function fingerprintQso(q){const canonical=[q.myCallsign,q.theirCallsign,q.qsoDatetimeUtc,q.frequencyHz??'',q.mode].join('|'),buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));return[...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function rowToItem(r){return{id:r.id,myCallsign:r.my_callsign,theirCallsign:r.their_callsign,qsoDatetime:r.qso_datetime_utc,frequency:r.frequency_display,frequencyHz:r.frequency_hz,band:r.band,mode:r.mode,rstSent:r.rst_sent,rstReceived:r.rst_received,grid:r.their_grid??r.my_grid,myGrid:r.my_grid,theirGrid:r.their_grid,myQth:r.my_qth,theirQth:r.their_qth,myEquipment:r.my_equipment,theirEquipment:r.their_equipment,myAntenna:r.my_antenna,theirAntenna:r.their_antenna,myPower:r.my_power_w===null?null:String(r.my_power_w),theirPower:r.their_power_w===null?null:String(r.their_power_w),notes:r.notes,weather:r.weather,theirWeather:r.their_weather,qslSent:Boolean(r.qsl_sent),qslSentAt:r.qsl_sent_at,qslReceived:Boolean(r.qsl_received),qslReceivedAt:r.qsl_received_at,source:r.managed_by,isPublic:Boolean(r.is_public),createdAt:r.created_at,updatedAt:r.updated_at}}
export function insertQsoStatement(db,id,q,fingerprint,managedBy,now){return db.prepare(`INSERT OR IGNORE INTO qsos(id,my_callsign,their_callsign,qso_datetime_utc,frequency_hz,frequency_display,band,mode,rst_sent,rst_received,my_qth,their_qth,my_grid,their_grid,my_equipment,their_equipment,my_antenna,their_antenna,my_power_w,their_power_w,notes,weather,their_weather,qsl_sent,qsl_sent_at,qsl_received,qsl_received_at,is_public,managed_by,fingerprint,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,q.myCallsign,q.theirCallsign,q.qsoDatetimeUtc,q.frequencyHz,q.frequencyDisplay,q.band,q.mode,q.rstSent,q.rstReceived,q.myQth,q.theirQth,q.myGrid,q.theirGrid,q.myEquipment,q.theirEquipment,q.myAntenna,q.theirAntenna,q.myPowerW,q.theirPowerW,q.notes,q.weather,q.theirWeather,q.qslSent,q.qslSentAt,q.qslReceived,q.qslReceivedAt,q.isPublic,managedBy,fingerprint,now,now)}
export function updateQsoStatement(db,id,q,fingerprint,now){return db.prepare(`UPDATE qsos SET my_callsign=?,their_callsign=?,qso_datetime_utc=?,frequency_hz=?,frequency_display=?,band=?,mode=?,rst_sent=?,rst_received=?,my_qth=?,their_qth=?,my_grid=?,their_grid=?,my_equipment=?,their_equipment=?,my_antenna=?,their_antenna=?,my_power_w=?,their_power_w=?,notes=?,weather=?,their_weather=?,qsl_sent=?,qsl_sent_at=?,qsl_received=?,qsl_received_at=?,is_public=?,fingerprint=?,updated_at=? WHERE id=? AND deleted_at IS NULL`).bind(q.myCallsign,q.theirCallsign,q.qsoDatetimeUtc,q.frequencyHz,q.frequencyDisplay,q.band,q.mode,q.rstSent,q.rstReceived,q.myQth,q.theirQth,q.myGrid,q.theirGrid,q.myEquipment,q.theirEquipment,q.myAntenna,q.theirAntenna,q.myPowerW,q.theirPowerW,q.notes,q.weather,q.theirWeather,q.qslSent,q.qslSentAt,q.qslReceived,q.qslReceivedAt,q.isPublic,fingerprint,now,id)}
